/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestilRouteImport } from './routes/bestil'
import { Route as HandelsbetingelserRouteImport } from './routes/handelsbetingelser'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KurvRouteImport } from './routes/kurv'
import { Route as OmRouteImport } from './routes/om'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdukterIndexRouteImport } from './routes/produkter.index'
import { Route as ProdukterSlugRouteImport } from './routes/produkter.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestilRoute = BestilRouteImport.update({
  id: '/bestil',
  path: '/bestil',
  getParentRoute: () => rootRouteImport,
} as any)
const HandelsbetingelserRoute = HandelsbetingelserRouteImport.update({
  id: '/handelsbetingelser',
  path: '/handelsbetingelser',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KurvRoute = KurvRouteImport.update({
  id: '/kurv',
  path: '/kurv',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterIndexRoute = ProdukterIndexRouteImport.update({
  id: '/produkter/',
  path: '/produkter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterSlugRoute = ProdukterSlugRouteImport.update({
  id: '/produkter/$slug',
  path: '/produkter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestil': typeof BestilRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/kurv': typeof KurvRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produkter/$slug': typeof ProdukterSlugRoute
  '/produkter/': typeof ProdukterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestil': typeof BestilRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/kurv': typeof KurvRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produkter/$slug': typeof ProdukterSlugRoute
  '/produkter': typeof ProdukterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestil': typeof BestilRoute
  '/handelsbetingelser': typeof HandelsbetingelserRoute
  '/kontakt': typeof KontaktRoute
  '/kurv': typeof KurvRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/produkter/$slug': typeof ProdukterSlugRoute
  '/produkter/': typeof ProdukterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestil'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/kurv'
    | '/om'
    | '/sitemap.xml'
    | '/produkter/$slug'
    | '/produkter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestil'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/kurv'
    | '/om'
    | '/sitemap.xml'
    | '/produkter/$slug'
    | '/produkter'
  id:
    | '__root__'
    | '/'
    | '/bestil'
    | '/handelsbetingelser'
    | '/kontakt'
    | '/kurv'
    | '/om'
    | '/sitemap.xml'
    | '/produkter/$slug'
    | '/produkter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestilRoute: typeof BestilRoute
  HandelsbetingelserRoute: typeof HandelsbetingelserRoute
  KontaktRoute: typeof KontaktRoute
  KurvRoute: typeof KurvRoute
  OmRoute: typeof OmRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdukterSlugRoute: typeof ProdukterSlugRoute
  ProdukterIndexRoute: typeof ProdukterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestil': {
      id: '/bestil'
      path: '/bestil'
      fullPath: '/bestil'
      preLoaderRoute: typeof BestilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handelsbetingelser': {
      id: '/handelsbetingelser'
      path: '/handelsbetingelser'
      fullPath: '/handelsbetingelser'
      preLoaderRoute: typeof HandelsbetingelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurv': {
      id: '/kurv'
      path: '/kurv'
      fullPath: '/kurv'
      preLoaderRoute: typeof KurvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter/': {
      id: '/produkter/'
      path: '/produkter'
      fullPath: '/produkter/'
      preLoaderRoute: typeof ProdukterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter/$slug': {
      id: '/produkter/$slug'
      path: '/produkter/$slug'
      fullPath: '/produkter/$slug'
      preLoaderRoute: typeof ProdukterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestilRoute: BestilRoute,
  HandelsbetingelserRoute: HandelsbetingelserRoute,
  KontaktRoute: KontaktRoute,
  KurvRoute: KurvRoute,
  OmRoute: OmRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdukterSlugRoute: ProdukterSlugRoute,
  ProdukterIndexRoute: ProdukterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
